<?php include('include/header.php') ?>

    <section class="sec1 innerBanner AboutUsBanner">
        <div class="container">
            <div class="row">
                <div class="col-md-12 bannertextLeft">
                    <div class="bannerTextInner">
                        <h1>
                            Privacy Policy
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="sec3 aboutSec2Content">
        <div class="container">
            <div class="row">
                <div class="col-md-12 innerPageDefaultContent bookContentmain">
                    <h3 class="heading2">1. Introduction</h3>
                    <p>
                        Welcome to Blue Pen Publishing.</p>

                    <p>Blue Pen Publishing respects your privacy. Our Privacy Policy will be revised on a timely
                        basis
                        to
                        meet our service's updated practices and legislative requirements. Our Privacy Policy's terms
                        align
                        with the Terms and Conditions that govern our website.</p>

                    <p>Before initiating the Privacy Policy, please note the use of terms “us”, “we”, “service”, and
                        “our”
                        will be used to refer to the www.theuniversalwriters.com</p>

                    <p>The Privacy Policy oversees your visit to our website and gives an insight into our data
                        collection,
                        sharing, and disclosing processes after you have visited www.theuniversalwriters.com. The terms
                        of
                        the Privacy Policy will be in full effect from the moment you visit our website.</p>

                    <p>The data collected from the visit is used to improve our services and offer an improved user
                        experience. By employing our service, you agree to the collection and use of data, as per the
                        conditions of the policy.</p>

                    <h3 class="heading2">2. Terminologies</h3>
                    <p>The term ‘Service’ refers to Blue Pen Publishing.</p>
                    <p>The term ’Personal Data’ refers to the information that can be used to identify an individual.
                        Personal data can include but is not limited to your name, address, email, contact number, and
                        bank
                        details.</p>
                    <p>The term ‘Usage Data’ refers to the automated accumulation of data generated by the visitation to
                        The
                        Universal Writers. This information can include but is not limited to the duration spent on the
                        page.</p>
                    <p>The term ‘Cookies’ refers to the blocks of data from a website that a web browser stores and
                        reclaims
                        at a later stage. Cookies inform the servers about a user’s return to a specific webpage.</p>
                    <p>The term ‘Data Controller’ refers to the legal individual(s) that determine the objective and
                        approach of using and processing the accumulated personal data. According to the terms of this
                        Privacy Policy, Blue Pen Publishing is the data controller of your data.</p>
                    <p
                    >The term ‘Data Processor’ refers to the legal individual(s) that process the data for the Data
                        Controller to reach more effective results. Blue Pen Publishing may appoint the services of
                        Data
                        Processors to integrate more expediency in your experience with our website.</p>
                    <p>The term ‘Data Subject’ refers to the individual whose data is being collected</p>
                    <p>The term ‘User’ is referred to the individual(s) using our service.</p>
                    <h3 class="heading2">3. Information Accumulation and Use</h3>
                    <p>Blue Pen Publishing collects different categories of data to provide a better service. The
                        following type of information is gathered by Blue Pen Publishing.</p>
                    <h4 class="heading4">Personal Data</h4>
                    <p>Blue Pen Publishing may collect and store your Personal Data, which includes but is not
                        limited
                        to
                        the ensuing:</p>
                    <ul>
                        <li>Your full name</li>
                        <li>Your email address</li>
                        <li>Your phone number</li>
                        <li>Your complete address</li>
                        <li>Cookies and usage data</li>
                    </ul>
                    <p>Blue Pen Publishing may collect your Personal Data via direct contact, newsletters, marketing
                        or
                        promotional materials, and other information. You have full liberty to avoid providing this
                        information, but that can limit the full extent of services we provide.</p>
                    <h4 class="heading4">Usage Data</h4>
                    <p>When you visit Blue Pen Publishing, your browser may automatically collect “Usage Data”. This
                        information can include, but is not limited to, the ensuing:</p>
                    <ul>
                        <li>Your device’s IP address</li>
                        <li>The date and time for the visit</li>
                        <li>Time spent on Blue Pen Publishing and its pages</li>
                        <li>Other diagnostic identifiers</li>
                    </ul>
                    <h4 class="heading4">Location Data</h4>
                    <p>Blue Pen Publishing may collect and store information about the location of your visit with
                        your
                        permission. This data can help us provide customized services.</p>
                    <h4 class="heading4">Cookies Data</h4>
                    <p>Blue Pen Publishing may track cookies or use similar technologies, including but not limited
                        to
                        beacons, tags, and scripts, to analyze your interaction with our website. You can disable the
                        cookies on your browser to prevent this type of data collection. However, this may limit your
                        ability to access some components of our service.</p>
                    <p>Blue Pen Publishing may collect:</p>
                    <ul>
                        <li>Session Cookies</li>
                        <li>Preference Cookies</li>
                        <li>Security Cookies</li>
                        <li>Advertising Cookies</li>
                    </ul>
                    <h4 class="heading4">Other Data</h4>
                    <p>Blue Pen Publishing may also collect information about your age, sex, place of birth,
                        passport
                        details, citizenship, registration, address, contact information, educational documents,
                        qualification, professional training, employment agreements, NDAs, marital status, social
                        security
                        number or any other taxpayer identification, and office location and other such information that
                        is
                        mandatory for the service.</p>
                    <h3 class="heading2">5. Purpose of Data Collection</h3>
                    <p>Blue Pen Publishing collects data to use in multiple instances:</p>
                    <ul>
                        <li>To offer an improved service quality</li>
                        <li>To provide an update on changes to the service</li>
                        <li>To offer improved customer service</li>
                        <li>To carry out detailed analysis to enhance customer experience</li>
                        <li>To observe service usage</li>
                        <li>To identify, avert, and resolve technical problems</li>
                        <li>To meet other objectives</li>
                        <li>To ensure that the terms of the agreement with the service are met and users entering into
                            our
                            service are well-informed about what the contract entails. Including maintaining records of
                            information about billing and collection
                        </li>
                        <li>To inform you of updates on your account or subscription to our service</li>
                        <li>To inform you of the latest news regarding Blue Pen Publishing, including but not
                            limited
                            to
                            news, discount offers, and other information about the extension of our services
                        </li>
                        <li>To meet any other objective with your permission.</li>
                    </ul>
                    <h3 class="heading2">6. Data Storage</h3>
                    <p>Blue Pen Publishing will collect and store your data for a necessary duration to ensure all
                        purposes stated in this Privacy Policy are met. Your personal data will be stored in a secure
                        manner, aligning with the legal requirements and state policies.</p>
                    <p>Your usage data will also be stored for a temporary period of time to carry out an internal
                        analysis.
                        However, in cases of legal intervention, we are mandated by the law to store the usage data for
                        a
                        longer time duration.</p>
                    <h3 class="heading2">7. Data Transfer</h3>
                    <p>Blue Pen Publishing will make sure that your data remains protected from any external access.
                        Our
                        security measures certify that the data is treated securely and is not transferred to any
                        organization without your consent. In case a transfer of data is required, in situations
                        including
                        but not limited to a merger or reliance on a third-party payment provider, we ensure that data
                        transfer takes place with enforced security controls.</p>
                    <h3 class="heading2">8. Disclosure of Data</h3>
                    <p>Your personal data may be disclosed in the following cases:</p>
                    <h4 class="heading4">Law Enforcement</h4>
                    <p>We must legally submit your personal information to law enforcement authorities upon
                        intervention.</p>
                    <h4 class="heading4">Mergers and Business Acquisitions</h4>
                    <p>In case Blue Pen Publishing is acquired in a merger or asset sale, your personal data may be
                        transferred.</p>
                    <h4 class="heading4">Other Instances</h4>
                    <p>Your data may also be disclosed to third-party services in the following cases:</p>
                    <ul>
                        <li>Your information is required by Blue Pen Publishing’ subsidiaries and affiliates</li>
                        <li>Your information is required by contractors or other third-party service providers who
                            upkeep
                            our services
                        </li>
                        <li>To meet the objectives of the information, submitted with your consent</li>
                    </ul>
                    <h3 class="heading2">9. Data Security </h3>
                    <p>Blue Pen Publishing ensures that your data is collected, stored, and transferred in an
                        exceptionally secure manner.</p>
                    <h3 class="heading2"> 10. Third-Party Services</h3>
                    <p>Blue Pen Publishing may appoint third-party companies and resources to enhance the quality of
                        any
                        component of our service, including but not limited to website optimization, payment processing,
                        and
                        more. The third-party companies will only be provided with the relevant data that is necessary
                        to
                        carry out their assigned responsibility. We will not disclose data for any other purpose.</p>
                    <h3 class="heading2">11. Analytics</h3>
                    <p>Blue Pen Publishing may employ third-party service providers, including but not limited to
                        Google
                        Analytics, to assess our services.</p>
                    <h3 class="heading2">12. CI/CD tools</h3>
                    <p>Blue Pen Publishing may employ third-party services to automate service development
                        procedures.</p>
                    <h3 class="heading2">13. Behavioral Remarketing</h3>
                    <p>Blue Pen Publishing may use remarketing facilities to promote our services on other websites
                        once
                        you have visited our services. We may employ third-party vendors and cookies to educate,
                        optimize
                        and display advertisements that reflect the behavior showcased on your visit to our website.</p>
                    <h3 class="heading2">14. Payment</h3>
                    <p>Blue Pen Publishing may extend paid services within our Service. In such scenarios, we employ
                        third-party payment processors who operate in accordance with their own Privacy Policy. The
                        payment
                        processing services we work with oblige to the regulations set by PCI-DSS and PCI Security
                        Standards
                        Council.</p>
                    <h3 class="heading2">15. External Linking</h3>
                    <p>Blue Pen Publishing may feature external links that connect you to a third-party website.
                        Upon
                        visiting the said page, we recommend reading their Privacy Policies, as Blue Pen Publishing
                        does
                        not take any responsibility for the content, behavior, or activities performed by any other
                        website
                        that we link to.</p>
                    <h3 class="heading2">16. Age of Consent</h3>
                    <p>Blue Pen Publishing only accepts Personal Information from individuals above the age of
                        consent
                        as
                        stated by the State of residence. We do not collect any information from children under the age
                        of
                        consent. If a user has provided such information, without our knowledge, we take immediate
                        measures
                        to cancel their subscriptions and delete all their records.</p>
                    <h3 class="heading2">17. Amendments and Updates</h3>
                    <p>Blue Pen Publishing has full permission to update, modify, and alter its Privacy Policy at
                        any
                        given time without notifying you of the change. We urge you to visit the Privacy Policy page on
                        www.theuniversalwriters.com to become updated with the changes in the agreement. The effective
                        date
                        is mentioned at the top of our Privacy Policy page to signify the last modification to the
                        policy.</p>
                    <h3 class="heading2">18. Contact Us</h3>
                    <p>If you have additional queries or concerns regarding Blue Pen Publishing’ Privacy Policy,
                        feel
                        free
                        to chat with us. You can send us an email at: <a href=mailto:info@abc.com>info@abc.com</a>
                    </p>
                </div>
            </div>
        </div>
    </section>


    <?php include('include/footer.php') ?>